# Generated by Django 5.1 on 2024-08-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='user')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('info', models.TextField(verbose_name='info')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
